version: '3.9'

services:

  redis-master:
    image: redis:7.2
    hostname: redis-master
    ports:
      - '${REDIS_MASTER_PORT}:6379'

  redis-slave:
    image: redis:7.2
    hostname: redis-slave
    ports:
      - '${REDIS_SLAVE_PORT}:6379'
    command: redis-server --slaveof redis-master 6379
